# Generated by Django 4.2.4 on 2023-08-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("comments", "0005_comment_deleted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="data",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="level",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="comment",
            name="lft",
            field=models.PositiveIntegerField(editable=False),
        ),
        migrations.AlterField(
            model_name="comment",
            name="rght",
            field=models.PositiveIntegerField(editable=False),
        ),
    ]
