# Generated by Django 3.2.9 on 2022-01-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0008_auto_20200708_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='data',
            field=models.JSONField(null=True),
        ),
    ]
